import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { runFeatureDevWorkflow } from '../src/agent/workflow.js';
import type { ModelProvider } from '../src/providers/base.js';
import type { ToolContext } from '../src/tools/types.js';

test('feature workflow drives implementation steps and adds rework step for fixNow', async () => {
  const root = await mkdtemp(join(tmpdir(), 'claudetest-implflow-'));
  await writeFile(join(root, 'src.txt'), 'content', 'utf8');

  const provider: ModelProvider = {
    name: 'mock',
    async createResponse(input) {
      const prompt = input.systemPrompt ?? '';
      if (prompt.includes('code-explorer')) {
        return {
          text: JSON.stringify({
            summary: 'explored',
            findings: ['entry found'],
            entryPoints: ['src/cli/app.tsx'],
            relevantPaths: ['src/agent/loop.ts'],
            suggestedFiles: ['src/agent/loop.ts'],
            risks: [],
            confidence: 0.8
          }),
          stopReason: 'final'
        };
      }
      if (prompt.includes('code-architect')) {
        return {
          text: JSON.stringify({
            summary: 'plan',
            recommendedApproach: 'modify loop',
            filesToModify: ['src/agent/loop.ts'],
            filesToCreate: [],
            implementationSteps: ['step1', 'step2'],
            tradeoffs: ['tradeoff1'],
            confidence: 0.9
          }),
          stopReason: 'final'
        };
      }
      if (prompt.includes('implementation-step executor')) {
        return {
          text: JSON.stringify({
            patches: [
              {
                filePath: 'src/agent/loop.ts',
                newContent: '// generated by test\n',
                reason: 'apply minimal test patch'
              }
            ]
          }),
          stopReason: 'final'
        };
      }
      if (prompt.includes('strict validation pass')) {
        return {
          text: JSON.stringify([{ title: 'high bug', keep: true }]),
          stopReason: 'final'
        };
      }
      return {
        text: JSON.stringify({
          summary: 'review done',
          findings: [
            {
              title: 'high bug',
              whyItMatters: 'important',
              evidence: 'src/agent/loop.ts',
              confidence: 0.95,
              category: 'bug'
            }
          ],
          confidence: 0.95
        }),
        stopReason: 'final'
      };
    }
  };

  const ctx: ToolContext = {
    approval: { requestApproval: async () => true },
    workspaceRoot: root,
    readMaxBytes: 10000,
    shellEnabled: true,
    writeEnabled: true
  };

  const out = await runFeatureDevWorkflow({
    task: '/feature test',
    provider,
    model: 'mock',
    toolContext: ctx
  });

  assert.equal(out.state.approvalGranted, true);
  assert.ok((out.state.selectedPlan?.implementationSteps.length ?? 0) >= 3);
  assert.ok(out.state.stepExecutionResults.some((r) => r.writesApplied > 0));
  assert.ok(
    out.actionableNextSteps.some(
      (s) => s.includes('Rework step completed') || s.includes('Rework step blocked')
    )
  );
});
